// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"go-lamp.autonomous.ai/internal/beclient"
	"go-lamp.autonomous.ai/internal/device"
	"go-lamp.autonomous.ai/internal/network"
	"go-lamp.autonomous.ai/internal/openclaw"
	"go-lamp.autonomous.ai/internal/resetbutton"
	"go-lamp.autonomous.ai/lib/mqtt"
	"go-lamp.autonomous.ai/server/config"
	http4 "go-lamp.autonomous.ai/server/device/delivery/gpio"
	http3 "go-lamp.autonomous.ai/server/device/delivery/http"
	"go-lamp.autonomous.ai/server/device/delivery/mqtt"
	"go-lamp.autonomous.ai/server/health/delivery/http"
	http2 "go-lamp.autonomous.ai/server/network/delivery/http"
	"go-lamp.autonomous.ai/server/openclaw/delivery/sse"
	http5 "go-lamp.autonomous.ai/server/sensing/delivery/http"
)

// Injectors from wire.go:

func InitializeServer() (*Server, error) {
	configConfig := config.ProvideConfig()
	healthHandler := http.ProvideHealthHandler()
	service := network.ProvideService(configConfig)
	openclawService := openclaw.ProvideService(configConfig)
	client := beclient.ProvideClient(configConfig)
	deviceService := device.ProvideService(configConfig, service, openclawService, client)
	networkHandler := http2.ProvideNetworkHandler(configConfig, service, deviceService)
	deviceHandler := http3.ProvideDeviceHandler(deviceService, service)
	mqttConfig := config.ProvideMQTTConfig(configConfig)
	factory, err := mqtt.ProvideFactory(mqttConfig)
	if err != nil {
		return nil, err
	}
	deviceMQTTHandler := mqtthandler.ProvideDeviceMQTTHandler(configConfig, factory, deviceService, service)
	deviceGPIOHandler := http4.ProvideDeviceGPIOHandler(configConfig, service, openclawService)
	openClawHandler := sse.ProvideOpenClawHandler(openclawService)
	sensingHandler := http5.ProvideSensingHandler(openclawService)
	resetbuttonService := resetbutton.ProvideServiceOptional()
	server := ProvideServer(configConfig, healthHandler, networkHandler, deviceHandler, deviceMQTTHandler, deviceGPIOHandler, openClawHandler, sensingHandler, deviceService, openclawService, service, resetbuttonService, factory)
	return server, nil
}
