// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"go-lamp.autonomous.ai/internal/beclient"
	"go-lamp.autonomous.ai/internal/device"
	"go-lamp.autonomous.ai/internal/led"
	"go-lamp.autonomous.ai/internal/llm"
	"go-lamp.autonomous.ai/internal/network"
	"go-lamp.autonomous.ai/internal/openclaw"
	"go-lamp.autonomous.ai/internal/resetbutton"
	"go-lamp.autonomous.ai/lib/mqtt"
	"go-lamp.autonomous.ai/server/config"
	http6 "go-lamp.autonomous.ai/server/device/delivery/gpio"
	http4 "go-lamp.autonomous.ai/server/device/delivery/http"
	http5 "go-lamp.autonomous.ai/server/device/delivery/mqtt"
	http8 "go-lamp.autonomous.ai/server/gws/delivery/http"
	"go-lamp.autonomous.ai/server/health/delivery/http"
	http2 "go-lamp.autonomous.ai/server/led/delivery/http"
	http7 "go-lamp.autonomous.ai/server/llm/delivery/http"
	http3 "go-lamp.autonomous.ai/server/network/delivery/http"
	"go-lamp.autonomous.ai/server/openclaw/delivery/sse"
)

// Injectors from wire.go:

func InitializeServer() (*Server, error) {
	configConfig := config.ProvideConfig()
	healthHandler := http.ProvideHealthHandler()
	driver, err := led.ProvideDriver()
	if err != nil {
		return nil, err
	}
	engine := led.ProvideEngine(driver)
	ledHandler := http2.ProvideLedHandler(engine)
	service := network.ProvideService(configConfig, engine)
	llmService := llm.ProvideService(configConfig)
	openclawService := openclaw.ProvideService(configConfig, llmService)
	client := beclient.ProvideClient(configConfig)
	deviceService := device.ProvideService(configConfig, service, engine, openclawService, client)
	networkHandler := http3.ProvideNetworkHandler(configConfig, service, deviceService)
	deviceHandler := http4.ProvideDeviceHandler(deviceService, service, engine)
	mqttConfig := config.ProvideMQTTConfig(configConfig)
	factory, err := mqtt.ProvideFactory(mqttConfig)
	if err != nil {
		return nil, err
	}
	deviceMQTTHandler := http5.ProvideDeviceMQTTHandler(configConfig, factory, deviceService, service)
	deviceGPIOHandler := http6.ProvideDeviceGPIOHandler(configConfig, service, openclawService, engine)
	llmHandler := http7.ProvideLLMHandler(llmService)
	gwsHandler := http8.ProvideGWSHandler(deviceMQTTHandler)
	openClawHandler := sse.ProvideOpenClawHandler(engine)
	resetbuttonService := resetbutton.ProvideServiceOptional()
	server := ProvideServer(configConfig, healthHandler, ledHandler, networkHandler, deviceHandler, deviceMQTTHandler, deviceGPIOHandler, llmHandler, gwsHandler, openClawHandler, deviceService, openclawService, service, engine, resetbuttonService, factory)
	return server, nil
}
